# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_auto_20171206_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 19, 16, 59, 198936, tzinfo=utc)),
        ),
    ]
